### ISSUE TITLE
Realizar deploy do projeto, em algum servidor

### ISSUE THREAD

**Issue by pedro21900** [pedro21900/fase_1_tech_challenge#2]

**Comment by muhlucas** [comment]
Realizei o deploy na aws, implementando o github actions https://github.com/muhlucas/embrapa_tech_challenge_fiap

**Comment by muhlucas** [comment]
Realizei o deploy na aws, implementando o github actions https://github.com/muhlucas/embrapa_tech_challenge_fiap
