### ISSUE TITLE
Ajustar documentação do README.md para inicialização do projeto e explicação do mesmo

### ISSUE THREAD

**Issue by pedro21900** [pedro21900/fase_1_tech_challenge#3]

**Comment by muhlucas** [comment]
Adicionei a um fork, uma nova documentação https://github.com/muhlucas/embrapa_tech_challenge_fiap

**Comment by muhlucas** [comment]
Adicionei a um fork, uma nova documentação https://github.com/muhlucas/embrapa_tech_challenge_fiap
